services:
  xampp:
    image: tomsik68/xampp
    container_name: xampp_container
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./ssl/localhost.crt:/opt/lampp/ssl/localhost.crt
      - ./ssl/localhost.key:/opt/lampp/ssl/localhost.key
      - ./ssl/httpd-ssl.conf:/opt/lampp/etc/extra/httpd-ssl.conf
      - ./src:/opt/lampp/htdocs
      - ./config/httpd.conf:/opt/lampp/etc/httpd.conf
      - ./composer:/usr/local/bin/composer

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    env_file:
      - .env
    environment:
      PMA_HOST: ${ip}
      PMA_PORT: ${port}
#      PMA_USER: ${user}
#      PMA_PASSWORD: ${password}
    ports:
      - "8081:80"