services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${db}
      MYSQL_USER: ${user}
      MYSQL_PASSWORD: ${password}
      MYSQL_ROOT_PASSWORD: ${password}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    env_file:
      - .env
    environment:
      PMA_HOST: ${ip}
      PMA_PORT: ${port}
    #      PMA_USER: ${user}
    #      PMA_PASSWORD: ${password}
    ports:
      - "8082:80"
