name: Dockerfile

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
#      - .github/workflows/**

  jobs:
    build:
      environment: back-end
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Docker Build
            run: |
              docker build -t lmao1415/ltw .

        - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push Docker image
            run: |
              docker push lmao1415/ltw

